#version for config and support version 18
version: '3.6'

services:

  apache2-modsec:
    image: miguelwill/debian7-apache-php
    depends_on:
      - db
    volumes:
       - www:/var/www
    restart: always
    environment:
      TZ: America/Santiago
      #RELAY_HOST: 172.43.12.15
    ports:
      - 80:80
      - 443:443

  db:
    image: mariadb:10.3
    restart: always
    volumes:
       - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: l4kj2l3jk4
      MYSQL_DATABASE: sitiodb
      MYSQL_USER: sitiouser
      MYSQL_PASSWORD: sitioPass
      TZ: America/Santiago
    ports:
      - 3306:3306

volumes:
  db-data:
  www:
